---

- fail:
    msg: "service_id is required"
  when: service_id is not defined

- name: Get python3 path
  shell: which python3
  register: python3_path

- name: start pythontron
  shell:
    cmd: nohup {{ python3_path.stdout }} /home/{{ ansible_user }}/{{ service_id }}/tron.py -c /home/{{ ansible_user }}/{{ service_id }}/config/app_config.json &
    chdir: /home/{{ ansible_user }}/{{ service_id }}

- include_tasks: cronjob.yml
